name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "406098c118e2496594dad846938a160c"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "10c77c38-698c-4ecf-9bf5-64b4b55f2d8b"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
